"""
Part 1: Legacy Address Transactions (P2PKH)

Workflow: This script handles the creation, signing, and broadcasting of Legacy (P2PKH) Bitcoin 
transactions. It runs against a local Bitcoin node in regtest mode.

Execution:

1. Node Setup:
    - Using Python's "requests" library, it connects to the local bitcoind instance to make RPC calls. 
    - Creates a new wallet to manage keys.
    - Generates a miner address and mines 101 blocks.(Since coinbase block rewards cannot be spent until 100 blocks are mined after it, this will let us use the rewards for actual transactions.)

2. Address Generation & Initial Funding:
    - Generates three Legacy (P2PKH) addresses A, B, and C.
    - Send bitcoins to Address A using the "sendtoaddress" RPC command and mines the block to confirm the UTXO.

3. Transaction from A to B:
    - Uses A's UTXO to create a transaction sending bitcoins to B.
    - Extracts Address B's challenge script (ScriptPubKey) from the transaction.
    - Signs the transaction, broadcasts it, and mines 1 block for confirmation.

4. Transaction from B to C:
    - Fetches B's new UTXO and creates a second transaction sending bitcoins to C.
    - Signs the transaction, then decodes the signed version to extract the response script (ScriptSig) that is generated by the private key.
    - Broadcasts the final transaction from B to C.
"""

import requests
import json
import time

# Configuration
RPC_USER = "myrpcuser"       
RPC_PASS = "myrpcpassword"   
RPC_PORT = 18443             
RPC_URL = f"http://127.0.0.1:{RPC_PORT}"

def rpc_call(method, params=[]):
    """Helper function to make RPC calls to bitcoind"""
    payload = {
        "jsonrpc": "1.0",
        "id": "cs216_assignment",
        "method": method,
        "params": params
    }
    response = requests.post(RPC_URL, json=payload, auth=(RPC_USER, RPC_PASS))
    if response.status_code != 200:
        print(f"Error calling {method}:", response.text)
        exit()
    return response.json()['result']

print("--- Starting CS 216 Part 1: Legacy Transactions ---")

# Wallet & Environment Setup
try:
    rpc_call("createwallet", ["lab_wallet"])
except:
    pass

miner_addr = rpc_call("getnewaddress", ["miner", "legacy"])
print("Mining initial blocks...")
rpc_call("generatetoaddress", [101, miner_addr])

# Generate addresses
addr_A = rpc_call("getnewaddress", ["Address_A", "legacy"])
addr_B = rpc_call("getnewaddress", ["Address_B", "legacy"])
addr_C = rpc_call("getnewaddress", ["Address_C", "legacy"])
print(f"\nAddress A: {addr_A}\nAddress B: {addr_B}\nAddress C: {addr_C}")

# Send bitcoins to Address A
print("\nFunding Address A with 5.0 BTC...")
rpc_call("sendtoaddress", [addr_A, 5.0])
rpc_call("generatetoaddress", [1, miner_addr]) 
time.sleep(1) 

# Transaction from A to B
print("\n--- Creating Transaction: A -> B ---")
utxo_A = rpc_call("listunspent", [1, 9999999, [addr_A]])[0]

inputs_AB = [{"txid": utxo_A['txid'], "vout": utxo_A['vout']}]
outputs_AB = {addr_B: 2.0, addr_A: 2.999} 

raw_tx_AB = rpc_call("createrawtransaction", [inputs_AB, outputs_AB])
decoded_AB = rpc_call("decoderawtransaction", [raw_tx_AB])

print("\n[REPORT REQUIREMENT] Challenge Script (ScriptPubKey) for Address B:")
for vout in decoded_AB['vout']:
    if vout['scriptPubKey'].get('address') == addr_B:
        print(json.dumps(vout['scriptPubKey'], indent=2))

signed_AB = rpc_call("signrawtransactionwithwallet", [raw_tx_AB])
txid_AB = rpc_call("sendrawtransaction", [signed_AB['hex']])
print(f"Broadcasted A -> B. TXID: {txid_AB}")

# Confirm the transaction so B actually receives the funds
rpc_call("generatetoaddress", [1, miner_addr])
time.sleep(1)

# Transaction from B to C
print("\n--- Creating Transaction: B -> C ---")
utxo_B = rpc_call("listunspent", [1, 9999999, [addr_B]])[0]

inputs_BC = [{"txid": utxo_B['txid'], "vout": utxo_B['vout']}]
outputs_BC = {addr_C: 1.0, addr_B: 0.999}

raw_tx_BC = rpc_call("createrawtransaction", [inputs_BC, outputs_BC])
signed_BC = rpc_call("signrawtransactionwithwallet", [raw_tx_BC])

# Decode the signed transaction to extract the response script
decoded_signed_BC = rpc_call("decoderawtransaction", [signed_BC['hex']])

print("\n[REPORT REQUIREMENT] Response Script (ScriptSig) from Address B:")
print(json.dumps(decoded_signed_BC['vin'][0]['scriptSig'], indent=2))


txid_BC = rpc_call("sendrawtransaction", [signed_BC['hex']])
print(f"Broadcasted B -> C. TXID: {txid_BC}")
print("\nPart 1 Code Execution Complete!")